* Rpm-spec mode 

** STARTED building
   :LOGBOOK:
   CLOCK: [2012-04-18 Wed 00:36]--[2012-04-18 Wed 00:40] =>  0:04
   :END:
    convert to osc or build options
** TODO rpm-tags-list
   Also add openSUSE related macros to rpm-tags-list look at
   build/parsePreamble.c:preambleList[] 

** TODO remove unneeded ones for opensuse and OBS
** TODO patches
 when adding patches make sure to follow http://en.opensuse.org/openSUSE:Packaging_Patches_guidelines
** BUG spec License
   - State "BUG"        from "DONE"       [2012-04-18 Wed 00:34]
   - State "DONE"       from "TODO"       [2012-03-30 Fri 23:57]
     use package name default for spec file License 
     with current year and rpm-spec-user-full-name and rpm-spec-mode-user-mail-address
*** TODO change spec licence to rpm-spec-licence defun
** TODO package license
   should meet http://en.opensuse.org/openSUSE:Packaging_guidelines#Licensing

** STARTED changelog
   :LOGBOOK:
   CLOCK: [2012-04-18 Wed 00:41]--[2012-04-18 Wed 01:26] =>  0:45
   :END:
    openSUSE uses packagename.changes file so do I need this
    part actually. The answer is no. However, I need to make sure osc vc or a
    similar action is done and 
** TODO Fixing spec file
[ ] If there are multiple BuildRequires then fix them so there is one per line. 
[ ] if the spec file already has the changelog
    entries then need to correct the part so there is a PACKAGENAME.changes
    file.
